name: Tests
on: [push]

jobs:
  # Runtime Tests
  runtime-test:
    name: Runtime Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: '1.10.1.763'

      - name: Build tests
        run: clojure -M:test

      - name: Run tests
        run: |
          node target/transit_test.js | tee test-out.txt
          grep -qxF '0 failures, 0 errors.' test-out.txt
